// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: helmrpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Helm_Ping_FullMethodName = "/helmrpc.Helm/Ping"
)

// HelmClient is the client API for Helm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Helm is served over a stdio-transported gRPC connection, wire-compatible
// with grpclib-transports' StdioChannel (raw HTTP/2 frames on stdin/stdout,
// no handshake, no socket).
type HelmClient interface {
	// Ping verifies the stdio transport end to end before any Helm rendering
	// logic is wired in.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type helmClient struct {
	cc grpc.ClientConnInterface
}

func NewHelmClient(cc grpc.ClientConnInterface) HelmClient {
	return &helmClient{cc}
}

func (c *helmClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Helm_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelmServer is the server API for Helm service.
// All implementations must embed UnimplementedHelmServer
// for forward compatibility.
//
// Helm is served over a stdio-transported gRPC connection, wire-compatible
// with grpclib-transports' StdioChannel (raw HTTP/2 frames on stdin/stdout,
// no handshake, no socket).
type HelmServer interface {
	// Ping verifies the stdio transport end to end before any Helm rendering
	// logic is wired in.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedHelmServer()
}

// UnimplementedHelmServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelmServer struct{}

func (UnimplementedHelmServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedHelmServer) mustEmbedUnimplementedHelmServer() {}
func (UnimplementedHelmServer) testEmbeddedByValue()              {}

// UnsafeHelmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelmServer will
// result in compilation errors.
type UnsafeHelmServer interface {
	mustEmbedUnimplementedHelmServer()
}

func RegisterHelmServer(s grpc.ServiceRegistrar, srv HelmServer) {
	// If the following call panics, it indicates UnimplementedHelmServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Helm_ServiceDesc, srv)
}

func _Helm_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Helm_ServiceDesc is the grpc.ServiceDesc for Helm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Helm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helmrpc.Helm",
	HandlerType: (*HelmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Helm_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helmrpc.proto",
}
