// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: helmrpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_helmrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helmrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_helmrpc_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_helmrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helmrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_helmrpc_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RenderRequest/RenderResponse both wrap a single opaque JSON payload rather
// than typed protobuf fields. google.protobuf.Struct was tried for the
// rendered resources first, but its wire format nests one submessage per
// object/array level -- deep CRD OpenAPI schemas (cert-manager,
// prometheus-operator, ...) routinely exceed upb's hardcoded ~100-message
// decode depth limit that way, and there's no public API to raise it. Once
// resources needed a JSON escape hatch anyway, keeping `values` (and every
// other field) as typed protobuf fields alongside it was just two encodings
// for the same job; this collapses both messages down to one. Adding or
// renaming a field is now a JSON-shape change on both sides, not a .proto
// regeneration.
type RenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   []byte                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_helmrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helmrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_helmrpc_proto_rawDescGZIP(), []int{2}
}

func (x *RenderRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

type RenderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseJson  []byte                 `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_helmrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helmrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_helmrpc_proto_rawDescGZIP(), []int{3}
}

func (x *RenderResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

var File_helmrpc_proto protoreflect.FileDescriptor

const file_helmrpc_proto_rawDesc = "" +
	"\n" +
	"\rhelmrpc.proto\x12\ahelmrpc\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"2\n" +
	"\rRenderRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\fR\vrequestJson\"5\n" +
	"\x0eRenderResponse\x12#\n" +
	"\rresponse_json\x18\x01 \x01(\fR\fresponseJson2v\n" +
	"\x04Helm\x123\n" +
	"\x04Ping\x12\x14.helmrpc.PingRequest\x1a\x15.helmrpc.PingResponse\x129\n" +
	"\x06Render\x12\x16.helmrpc.RenderRequest\x1a\x17.helmrpc.RenderResponseB-Z+github.com/lillecarl/easykubenix/helmrpc/pbb\x06proto3"

var (
	file_helmrpc_proto_rawDescOnce sync.Once
	file_helmrpc_proto_rawDescData []byte
)

func file_helmrpc_proto_rawDescGZIP() []byte {
	file_helmrpc_proto_rawDescOnce.Do(func() {
		file_helmrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helmrpc_proto_rawDesc), len(file_helmrpc_proto_rawDesc)))
	})
	return file_helmrpc_proto_rawDescData
}

var file_helmrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_helmrpc_proto_goTypes = []any{
	(*PingRequest)(nil),    // 0: helmrpc.PingRequest
	(*PingResponse)(nil),   // 1: helmrpc.PingResponse
	(*RenderRequest)(nil),  // 2: helmrpc.RenderRequest
	(*RenderResponse)(nil), // 3: helmrpc.RenderResponse
}
var file_helmrpc_proto_depIdxs = []int32{
	0, // 0: helmrpc.Helm.Ping:input_type -> helmrpc.PingRequest
	2, // 1: helmrpc.Helm.Render:input_type -> helmrpc.RenderRequest
	1, // 2: helmrpc.Helm.Ping:output_type -> helmrpc.PingResponse
	3, // 3: helmrpc.Helm.Render:output_type -> helmrpc.RenderResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helmrpc_proto_init() }
func file_helmrpc_proto_init() {
	if File_helmrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helmrpc_proto_rawDesc), len(file_helmrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helmrpc_proto_goTypes,
		DependencyIndexes: file_helmrpc_proto_depIdxs,
		MessageInfos:      file_helmrpc_proto_msgTypes,
	}.Build()
	File_helmrpc_proto = out.File
	file_helmrpc_proto_goTypes = nil
	file_helmrpc_proto_depIdxs = nil
}
