name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v35
      - name: Lint examples
        run: nix flake check ./docs/examples --print-build-logs
      - name: Validate against real kube-apiserver
        run: nix run ./docs/examples#packages.x86_64-linux.validationScript
      - name: Run tests
        run: nix develop -c python3 -m pytest -v --no-header
